lpass: add alias support
People have often asked for shortcuts to do certain common things with lpass,
or would like to select regex or substring as default string matching types.
Until now the best answer has been to use a shell alias.

This change adds a built-in alias feature similar to git aliases which
lets one set up custom commands or default switches by adding an
'alias.<commandname>' configuration.

Example usage:

        $ lpass show yahoo
        Error: Could not find specified account 'yahoo'.
        $ echo 'show -G' > ~/.lpass/alias.show
        Multiple matches found.
        [...]

Signed-off-by: Bob Copeland <copeland@lastpass.com>